version: '3.3'

volumes:
  foodgram_static:
  foodgram_media:
  front_data:

services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: ssprihodko/foodgram:latest
    restart: always
    volumes:
      - foodgram_static:/app/backend_static/
      - foodgram_media:/app/backend_media/
    depends_on:
      - db
    env_file:
      - ./.env
    depends_on:
      - db

  frontend: 
    image: ssprihodko/foodgram_front:v1
    restart: always
    volumes:
      - front_data:/app/result_build/
    depends_on:
      - web

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - foodgram_static:/var/html/static/
      - foodgram_media:/var/html/media/
    depends_on:
      - front
