version: '3.3'

volumes:
  db_data:
  static_value:
  media_value:

services:

  #db:
  #  image: postgres:13.0-alpine
  #  volumes:
  #    - db_data:/var/lib/postgresql/data/
  #  env_file:
  #    - ./.env

  backend:
    build: ../backend/
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    #depends_on:
    #  - db

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    #depends_on:
    #  - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/app/static/
      - media_value:/app/media/