# Generated by Django 3.0 on 2022-03-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220319_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity',
            name='measurement_unit',
            field=models.CharField(default=1, help_text='Единица измерения', max_length=10, verbose_name='Единица измерения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quantity',
            name='name',
            field=models.CharField(default=1, help_text='Ингредиент', max_length=200, verbose_name='Ингредиент'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='quantity',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='unique_ingredient'),
        ),
    ]
