# Generated by Django 3.0 on 2022-03-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('id',), 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='quantity',
            options={'verbose_name': 'Ингредиент рецепта', 'verbose_name_plural': 'Ингредиент рецепта'},
        ),
        migrations.AlterModelOptions(
            name='recipetag',
            options={'verbose_name': 'Тэг рецепта', 'verbose_name_plural': 'Тэги рецепта'},
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='measurement_unit',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='name',
        ),
    ]
