# Generated by Django 3.0 on 2022-03-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220322_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantity',
            old_name='quantity',
            new_name='amount',
        ),
    ]
