# Generated by Django 3.0 on 2022-03-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220322_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#00FF00', 'Лимонный'), ('#9400D3', 'Темно-фиолетовый'), ('#008000', 'Зеленый'), ('#00BFFF', 'Голубой')], help_text='Цвет', max_length=7, unique=True, verbose_name='Цвет'),
        ),
    ]
